. '/etc/zsh/zshrc.grml'
export GPG_TTY="$( tty )"
[[ -d '/home/common/apps' ]] && PATH="/home/common/apps:${PATH}"
[[ -d "${HOME}/bin" ]] && PATH="${HOME}/bin:${PATH}"
[[ -d "${HOME}/.local/bin" ]] && PATH="${HOME}/.local/bin:${PATH}"
(( EUID != 0 )) && { [[ -n "${PS1}" ]] && [[ -z "${TMUX}" ]] && tmux new-session -A -s 'main'; }
