fs.file-max = 9223372036854775807
fs.inotify.max_user_watches = 524288
kernel.dmesg_restrict = 1
net.core.default_qdisc = fq
net.ipv4.ip_forward = 0
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_syncookies = 1
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.forwarding = 0
