fs.file-max = 9223372036854775807
fs.inotify.max_user_watches = 524288
kernel.dmesg_restrict = 1
net.core.default_qdisc = fq
net.core.optmem_max = 40960
net.core.rmem_default = 8388608
net.core.rmem_max = 536870912
net.core.wmem_default = 8388608
net.core.wmem_max = 536870912
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.ip_forward = 0
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_syncookies = 1
