cluster.name: 'cluster.01'
node.name: 'node.01'
node.processors: 2
path.data: '/var/lib/elasticsearch'
path.logs: '/var/log/elasticsearch'
network.host: 127.0.0.1
http.port: 9200
discovery.type: single-node
action.auto_create_index: false
bootstrap.memory_lock: true
xpack.security.enabled: false
xpack.security.enrollment.enabled: true
xpack.security.http.ssl:
  enabled: true
  keystore.path: 'certs/http.p12'
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: 'certs/transport.p12'
  truststore.path: 'certs/transport.p12'
http.host: 127.0.0.1
