title: "UNIX AIK"
description: "UNIX Automated Installation Kit."

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"

twitter:
  username: "KitsuneSolar"
  card: summary

social:
  name: "Kitsune Solar"
  links:
    - https://kitsune.solar/
    - https://twitter.com/KitsuneSolar
    - https://linkedin.com/in/KitsuneSolar
    - https://github.com/KitsuneSolar
    - https://gitlab.com/KitsuneSolar

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap