title: 'Universal AIK'
description: 'Universal Automated Installation Kit (UAIK).'
remote_theme: 'pages-themes/minimal@v0.2.0'

defaults:
  - scope:
      path: ''
    values:
      image: ''

webmaster_verifications:
  google: ''
  yandex: ''

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
